apiVersion: batch/v1
kind: Job
metadata:
  name: pachyderm-config
spec:
  template:
    spec:
      containers:
      - name: config-pod
        image: pachyderm/config-pod:0.1
        command: [ "/config-pod" ]
        volumeMounts:
        - name: config
          mountPath: "/pachConfig"
      restartPolicy: Never
      volumes:
      - name: config
        secret: 
          secretName: pachyderm-config
  backoffLimit: 4

