apiVersion: v1
kind: Secret
metadata:
  name: pachyderm-config
stringData:
  # authConfig is the configuration for pachd as an OIDC client
  authConfig: |
    client_id: pachd 
    client_secret: notsecret
    issuer: http://localhost:30658/
    localhost_issuer: true
    redirect_uri: http://pachd:1657/authorization-code/callback
    scopes:
    - email
    - profile
    - groups
    - openid 

  # clusterRoleBindings is a set of user -> role mappings to apply
  clusterRoleBindings: |
    robot:test:
    - repoReader  

  # enterpriseClusters is the set of pachds covered by license service 
  enterpriseClusters: |
    - address: localhost:1650
      id: localhost
      secret: secret

  # enterpiseConfig points the pachd to a license service (in this case itself)
  enterpriseConfig: |
    id: localhost
    license_server: localhost:1650
    secret: secret

  # identityServiceConfig configures the OIDC provider
  identityServiceConfig: |  
    issuer: http://localhost:30658/

  # idps is the set of Identity Providers to support for logging in
  idps: |
    - id: test
      jsonConfig: '{"username": "admin", "password": "password"}'
      name: test
      type: mockPassword

  license: <PACH ENTERPRISE LICENSE> 

  # oidcClients is the set of OIDC clients registered with the OIDC provider
  oidcClients: |
    - id: pachyderm
      name: pachd
      secret: oidcsecret
      redirect_uris:
      - http://pachd:1657/authorization-code/callback

  # rootToken is the auth token used to communicate with the cluster as the root user
  rootToken: supersecrettoken
