version: 2.1

jobs:
  lint:
    docker:
      - image: golangci/golangci-lint:v1.43.0
    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      - run:
          name: run lint
          command: golangci-lint run --timeout 10m

  test:
    resource_class: large
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run: etc/testing/circle/install.sh
      - run: etc/testing/circle/start-minikube.sh
      - run: etc/testing/circle/deploy-pachyderm.sh
      - run: etc/testing/circle/test.sh
      - run:
         name: Dump debugging info in case of failure
         when: on_fail
         command: etc/testing/circle/kube_debug.sh

  release:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: etc/release.sh

workflows:
  circleci:
    jobs:
      - lint:
          filters:
            tags:
              only: /^\d+\.\d+$/
      - test:
          filters:
            tags:
              only: /^\d+\.\d+$/
      - release:
          requires:
            - lint
            - test
          filters:
            tags:
              only: /^\d+\.\d+$/
            branches:
              ignore: /.*/
