version: 2.1

jobs:
  lint:
    docker:
      - image: circleci/golang:1.16
    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      - run: "echo $(($(date +%s)/604800)) > current_week"
      - restore_cache:
          key: golang-lint-ci-{{ checksum "current_week" }}
      - run:
          name: install lint
          command: |
            if [[ ! -e /usr/local/bin/golangci-lint ]]; then
              cd /usr/local
              curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
                | sh -s v1.40.1
            fi
      - save_cache:
          paths:
            - /usr/local/bin/golangci-lint
          key: golang-lint-ci-{{ checksum "current_week" }}
      - run:
          name: run lint
          command: golangci-lint run --timeout 10m

  test:
    resource_class: large
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run: etc/testing/circle/install.sh
      - run: etc/testing/circle/start-minikube.sh
      - run: etc/testing/circle/deploy-pachyderm.sh
      - run: etc/testing/circle/test.sh
      - run:
         name: Dump debugging info in case of failure
         when: on_fail
         command: etc/testing/circle/kube_debug.sh

  release:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: etc/release.sh

workflows:
  circleci:
    jobs:
      - lint
      - test:
          filters:
            tags:
              only: /^\d+\.\d+$/
      - release:
          requires:
            - test
          filters:
            tags:
              only: /^\d+\.\d+$/
            branches:
              ignore: /.*/
